// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserManagementService.DataAccessLayer;

namespace UserManagementService.Migrations
{
    [DbContext(typeof(UserManagementContext))]
    [Migration("20220111181549_NewTestUsers")]
    partial class NewTestUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("UserManagementService.Models.ChiliUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChiliUserRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecretAnswer")
                        .HasColumnType("text");

                    b.Property<Guid>("SecretQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChiliUserRoleId");

                    b.HasIndex("SecretQuestionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0da09c36-50ac-44fb-a102-8b528bcbad51"),
                            ChiliUserRoleId = new Guid("39bf46f0-cc42-438f-866c-c20c393a307b"),
                            Email = "adminuser@chiliboard.de",
                            PasswordHash = "AQAAAAEAACcQAAAAEAdJXavdRynohCvJOvY2Wpv2Xq5S8KrDwzMmYZ7cgH5lHfIviLwUuVx8ZvUdRaFF/g==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 873, DateTimeKind.Local).AddTicks(7956),
                            SecretAnswer = "AQAAAAEAACcQAAAAEAud5bCLrgnTxxRZwEAaLE8m2/zbWig6pryJjG9AeJ7gmlZbhfVlKXlsgSHf1d27tw==",
                            SecretQuestionId = new Guid("f7f78ebd-22d5-4861-893e-7dceee4ee4fe"),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("bf9657c5-0827-44bb-b902-f627d24c0313"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "casualUser@web.de",
                            PasswordHash = "AQAAAAEAACcQAAAAEJl4hW6EYhnxkedXG/fCWJp9ayAkJ7jrjKxTKovZ9pLvve7cjw3lhqn1UbMifQJRow==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8733),
                            SecretAnswer = "AQAAAAEAACcQAAAAEF0IjRa51lQg6xDcSw0q5GuSYRfoSYu5BBQ9Oj8UMElwXqu05oJGJJM6XjxlpsU0UQ==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "CasualUser69420"
                        },
                        new
                        {
                            Id = new Guid("8c8dd0dd-a6b6-478d-a298-1011cb5bf060"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "catlover@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAECjj1TmdUDnBfqt7tWifyLxjBb6LVNQS/cxT0bgSiMKx3YKYQ1lBTDe66Bjaanarxw==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8743),
                            SecretAnswer = "AQAAAAEAACcQAAAAEFkcn8oRFRyC1ThHq20AuFE/jhSuDYUxiRuRqUCCuczpnGy2aC9mAZ/FCYlY7mUZRQ==",
                            SecretQuestionId = new Guid("f3124fb0-79ce-403b-8cd4-eceafaf2a0ff"),
                            UserName = "CatLover123"
                        },
                        new
                        {
                            Id = new Guid("0da09c36-50ac-44fb-a102-8b528bcbad58"),
                            ChiliUserRoleId = new Guid("39bf46f0-cc42-438f-866c-c20c393a307b"),
                            Email = "nis@chiliboard.de",
                            PasswordHash = "AQAAAAEAACcQAAAAEK+exn1vYmkvrp2Dr5j4K63J38U28w5sEKD/X1XUvfn7Nh51MjcbQnY5JPpY7oo4kA==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8694),
                            SecretAnswer = "AQAAAAEAACcQAAAAEM6XxJmfFqvjCoJAbIKHmw1Dy9MqTvybKNTNBNrNY1QxFTXAwUaQv5zOjFc6JvCwmw==",
                            SecretQuestionId = new Guid("f3124fb0-79ce-403b-8cd4-eceafaf2a0ff"),
                            UserName = "nis"
                        },
                        new
                        {
                            Id = new Guid("25ca7448-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "rcwil@att.net",
                            PasswordHash = "AQAAAAEAACcQAAAAEPFtngb5JKxmgauIVoVzvRcq5S0M+/tqUHyhs2aGzwN3D1cTTr9PC1Pe6emTmoiZKw==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8751),
                            SecretAnswer = "AQAAAAEAACcQAAAAEIzmIf8woR/vnYUEmNCJgl7ZbHpBCPlxQPdvjOEQSxQhuiJivX71QPZMH7WsWUCmqQ==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "rcwil"
                        },
                        new
                        {
                            Id = new Guid("25ca7696-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "pajas@sbcglobal.net",
                            PasswordHash = "AQAAAAEAACcQAAAAEF+V5vLhclRXxzC7V7RsEmX+ZppXOJVsAWSkHUjzRHHRHadKecizlJOUYCMfFuoa2w==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8757),
                            SecretAnswer = "AQAAAAEAACcQAAAAEG741f/9nNEEmhjsGuZEMjB9hRSquno0e19ouCkrRc8OeZqzvwm+Qg22VKnP1kilJA==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "pajas"
                        },
                        new
                        {
                            Id = new Guid("25ca77e0-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "kempsonc@comcast.net",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLHtQuoXxZpjIb9Haq+SCWN8dmWywhjZYTNwb+JHaW4mPbvcKORaWoWPaWDVgjm3A==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8765),
                            SecretAnswer = "AQAAAAEAACcQAAAAEMydsUyqq9ndISuZWsd3vV2M68MZDVw1HcKbvZcZ0h1CbRr9EUH20zAuOJkNz1sA+Q==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "kempsonc"
                        },
                        new
                        {
                            Id = new Guid("25ca7920-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "rnelson@sbcglobal.net",
                            PasswordHash = "AQAAAAEAACcQAAAAENSbcKei8yjFZpSGIiPom4nUkl5ZY5fKGUpfYwz5PSZ13B4Q15hYt+FN5iuLW1wYtg==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8771),
                            SecretAnswer = "AQAAAAEAACcQAAAAEEJ2aadah21YW5Qdk/lA7j8MfZbkUD8sCxlybSCFOukoGof9ajdLgN9qydf0nTHCoA==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "rnelson"
                        },
                        new
                        {
                            Id = new Guid("25ca7a4c-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "kempsonc@yahoo.ca",
                            PasswordHash = "AQAAAAEAACcQAAAAEFPc4RSpKFVziGSDRkJucy1l74X948PiVvamsRvvOzxPLyQSUeN5rVr5PJMKI0F2Eg==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8778),
                            SecretAnswer = "AQAAAAEAACcQAAAAEMhQ1+sr9s9CIY79rml2CZV5b1o9LE2G++/DA6DI4cMGLXlUA/2ta1bss/Qp2v/UsA==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "kempsonc"
                        },
                        new
                        {
                            Id = new Guid("25ca7d44-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "sharon@yahoo.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEPJJ8UMQ7dsDvuL+US6sEQ5vL9tZT8+9HK6G7OmKfolVD0v1krPtpXATbfvFsGGDTg==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8785),
                            SecretAnswer = "AQAAAAEAACcQAAAAEJqIIDEKTRWE6pPsR6tKgRmPUL/ImQLEqLhkVK1Z/E55fCb4nj2aSltL83OO+vEjpg==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "sharon"
                        },
                        new
                        {
                            Id = new Guid("25ca7e8e-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "moonlapse@comcast.net",
                            PasswordHash = "AQAAAAEAACcQAAAAECFNkKvCs+y0IsNSMXYwm6pzIied7oA5i2wQd+sO9NyqgrULOKuP3WxE4Lp2yuWxAA==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8792),
                            SecretAnswer = "AQAAAAEAACcQAAAAEJ6HOZ6HF/aGRfh1iSrZnb4YNel1urJ7EYw4Qe9Vf0/euc1gLtIz4AmHVTWJr2IWOA==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "moonlapse"
                        },
                        new
                        {
                            Id = new Guid("25ca7fa6-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "kspiteri@comcast.net",
                            PasswordHash = "AQAAAAEAACcQAAAAEKnEvj2zqp1LhbkVNFUqM57vZXoB20aHSOu5OXTXCBnlDQDys+ihsi/SMCpv6ELpRg==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8799),
                            SecretAnswer = "AQAAAAEAACcQAAAAEJMRzNWNZf7IOWVJcpYN8Wt7mGTFOJzTDju70Na4r+PP1hPgYzFHBRIeyQboOA2zYA==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "kspiteri"
                        },
                        new
                        {
                            Id = new Guid("25ca80d2-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "dinther@sbcglobal.net",
                            PasswordHash = "AQAAAAEAACcQAAAAEA5+Zus3u+9ZB/iIQQPsLnV89JZHD6r9B86OafYypreCvtTxY5NDr0G7F6weqUj4Dw==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8806),
                            SecretAnswer = "AQAAAAEAACcQAAAAECWoJc/+aP5gGEnK9tl6fskUODNmcmvAYJE/qMtLMPHKu5ODWfwZgCLkXB/Ug0CFGw==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "dinther"
                        },
                        new
                        {
                            Id = new Guid("25ca81f4-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "janneh@mac.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEBq0Mv1ZO5DYwl/204bAT+pYkWbAlo3I+QW8g98xxux3E9LcoHsDd2emwQGyJmq7dg==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8812),
                            SecretAnswer = "AQAAAAEAACcQAAAAEE/FeBsxjSTk1AuCAWBXlNDwxLyIKMGQB3ofmPEfi68VsLh/CyLsMsgbviX0kg3Wvw==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "janneh"
                        },
                        new
                        {
                            Id = new Guid("25ca8320-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "dwheeler@icloud.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEApkFXBuwBIacTy5sc1doviy1Tu4GEsStGjmn7JlbrsRAzt6tFiX2KqECASl7T9rfw==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8818),
                            SecretAnswer = "AQAAAAEAACcQAAAAENVt5rU6V7O6kcENgL72ZC4ZkleBcS0ASt1hE057vt5T752WE8rKQNFr22DXAlZ80Q==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "dwheeler"
                        },
                        new
                        {
                            Id = new Guid("25ca8442-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "violinhi@me.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEMCqqjf+ao7E96/Vb6HURR7J8jH90ERGgYwfmlR3vvWEqf9wB8AJAXwNQGPUMGu76g==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8825),
                            SecretAnswer = "AQAAAAEAACcQAAAAEDpVtj14iwLggyW579luKibypZcIkblCrWgvwsBriE3Lan6zbPW2zl4P/i2lCcwNTA==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "violinhi"
                        },
                        new
                        {
                            Id = new Guid("25ca856e-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "kewley@aol.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEHE0/1o41zNvbYcuf3W0i2u1Bq9WnFIroXJVqV7QN/OEmNvAZZG0EErY3ZZAJ9iKEA==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8830),
                            SecretAnswer = "AQAAAAEAACcQAAAAEEmwhG+lqKHy5xMyJE0IrKST1Wf5CgSAJNBFiiMFK8+FbXIr1usKk+5kREALmgkpBQ==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "kewley"
                        },
                        new
                        {
                            Id = new Guid("25ca896a-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "mfleming@mac.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEH0saf64rIf5Fi5+IpqKdw4/JX4oIzKoC1vSqIB7gWYnatuF66X28/s7wNXu301RmA==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8837),
                            SecretAnswer = "AQAAAAEAACcQAAAAEPbObPMEBJLy4XOwDvgBtmrk0Y5ki2Hzgew1ee4UHPv5NSuXRZyFq/0NA57a4NqIyw==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "mfleming"
                        },
                        new
                        {
                            Id = new Guid("25ca8aa0-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "kosact@hotmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ4e3mfuOtK4pEgWw2ji8q4r6mCiW5eDj4Qn851LbH3sRIPtsodJMzClfZtEVZ0Rww==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8844),
                            SecretAnswer = "AQAAAAEAACcQAAAAEAwixjdyIGk5iYyvCIX3z1qwLxWvPioApkD9hlFEsm9rXZ7qXFpU843FZLsuUOyWkw==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "kosact"
                        },
                        new
                        {
                            Id = new Guid("25ca8bcc-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "fudrucker@sbcglobal.net",
                            PasswordHash = "AQAAAAEAACcQAAAAEMc7slgeUJBR6EpORgv3ofA3cAbtyOqvnGenvZNY4nBgrXKASdqWTGBAIghSG9KUWw==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8850),
                            SecretAnswer = "AQAAAAEAACcQAAAAEEVjahbsl1OwvJuvQFjeJJJ+0foXX/UEGBIrgKOiS91JtWupyQTnDNztLkoBlvwKkw==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "fudrucker"
                        },
                        new
                        {
                            Id = new Guid("25ca8cf8-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "frosal@optonline.net",
                            PasswordHash = "AQAAAAEAACcQAAAAEBtu23Z3RYu/bJWr9JIR+ZGdFN8Uf1y3wR4Qacq8YuvKgHd83RuedwGoZ4UoKNq6Tw==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8858),
                            SecretAnswer = "AQAAAAEAACcQAAAAEAgHczcmV8RSYMiT4eM4qKLV0DWSTHlB5AQDjDfIubOji/V+jAHAYTkHD586LjoPMQ==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "frosal"
                        },
                        new
                        {
                            Id = new Guid("25ca8e24-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "gmcgath@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAENd79gojjfu9mehZ+5U+Lwoe5G0Ilwu5ZIez8KrijxqsrUnMy7/GhjRXtXHAk9sHiw==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8864),
                            SecretAnswer = "AQAAAAEAACcQAAAAECLuhC38SXntGJe/N0hmFMqzGLdJBngfndnU4/JSnBlvcjt4CjyGNFjxkBxQVUqkNQ==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "gmcgath"
                        },
                        new
                        {
                            Id = new Guid("25ca8f32-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "chaffar@mac.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEIPODGLMvXPegULfpKpiC2XTeai05C5KRxMUdBASD3H8PFlmGL4DfMOyF316GukktQ==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8870),
                            SecretAnswer = "AQAAAAEAACcQAAAAEIvZyQWcMgo2Pxrd99D09FTNJG65xkz+wHftyFmF3XPsJz8UMSXKmc2Qfz3nMNsUiA==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "chaffar"
                        },
                        new
                        {
                            Id = new Guid("25ca9040-72d4-11ec-90d6-0242ac120003"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "ilial@icloud.com",
                            PasswordHash = "AQAAAAEAACcQAAAAELotDZvHMMIifQJ/0BMp3S+zaSgwzgiIfxpcDG9YNFsvKD4UA7XcN30Ky8F6SOpGvQ==",
                            RegistrationDate = new DateTime(2022, 1, 11, 19, 15, 48, 876, DateTimeKind.Local).AddTicks(8876),
                            SecretAnswer = "AQAAAAEAACcQAAAAEDUMVEpuo/2ubRYRNrEPxYqwb2SgnXOcc/wAAadAbOrUaRNYzAz/QKBUHVV9Q2sbYA==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "ilial"
                        });
                });

            modelBuilder.Entity("UserManagementService.Models.ChiliUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Rolename")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39bf46f0-cc42-438f-866c-c20c393a307b"),
                            Rolename = "Admin"
                        },
                        new
                        {
                            Id = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Rolename = "DefaultChiliUser"
                        });
                });

            modelBuilder.Entity("UserManagementService.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UserManagementService.Models.SecurityQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SecurityQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3124fb0-79ce-403b-8cd4-eceafaf2a0ff"),
                            Question = "Was ist Ihr Lieblingsessen?"
                        },
                        new
                        {
                            Id = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            Question = "Wie lautet der Geburtsname Ihrer Mutter?"
                        },
                        new
                        {
                            Id = new Guid("f7f78ebd-22d5-4861-893e-7dceee4ee4fe"),
                            Question = "Wie lautet Ihre Lieblingsprimzahl?"
                        });
                });

            modelBuilder.Entity("UserManagementService.Models.ChiliUser", b =>
                {
                    b.HasOne("UserManagementService.Models.ChiliUserRole", "Role")
                        .WithMany()
                        .HasForeignKey("ChiliUserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagementService.Models.SecurityQuestion", "SecretQuestion")
                        .WithMany()
                        .HasForeignKey("SecretQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("SecretQuestion");
                });

            modelBuilder.Entity("UserManagementService.Models.RefreshToken", b =>
                {
                    b.HasOne("UserManagementService.Models.ChiliUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
