// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserManagementService.DataAccessLayer;

namespace UserManagementService.Migrations
{
    [DbContext(typeof(UserManagementContext))]
    [Migration("20220106072037_NewAdmin")]
    partial class NewAdmin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("UserManagementService.Models.ChiliUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChiliUserRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecretAnswer")
                        .HasColumnType("text");

                    b.Property<Guid>("SecretQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChiliUserRoleId");

                    b.HasIndex("SecretQuestionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0da09c36-50ac-44fb-a102-8b528bcbad51"),
                            ChiliUserRoleId = new Guid("39bf46f0-cc42-438f-866c-c20c393a307b"),
                            Email = "adminuser@chiliboard.de",
                            PasswordHash = "AQAAAAEAACcQAAAAEBzA6WvKNoJrYZJr2bNMv9nqVtizfSrZmfRPksxSV+nA6WHGvpMbTd0FYtVvHHQsnQ==",
                            RegistrationDate = new DateTime(2022, 1, 6, 8, 20, 36, 704, DateTimeKind.Local).AddTicks(5899),
                            SecretAnswer = "AQAAAAEAACcQAAAAENSqp3BOlNJvbUKU0+CnTXrooFYBg1GbtHwQuf4ZZgqstLdMSDGCHKb2V7dxW/95ow==",
                            SecretQuestionId = new Guid("f7f78ebd-22d5-4861-893e-7dceee4ee4fe"),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("bf9657c5-0827-44bb-b902-f627d24c0313"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "casualUser@web.de",
                            PasswordHash = "AQAAAAEAACcQAAAAEL3W+0Em9YCHPfSfuABXrpXT7RpdNcO1fH4RuRwoDiOW6+A3ocLlb/JGCfeHJrbAcQ==",
                            RegistrationDate = new DateTime(2022, 1, 6, 8, 20, 36, 707, DateTimeKind.Local).AddTicks(6223),
                            SecretAnswer = "AQAAAAEAACcQAAAAEDL1AMl5ZcIv4JJ6cX7YcLcVKt18GA/NZEJvDWVmKWdZ4t8ZFodRR33khqZ+PoF/aw==",
                            SecretQuestionId = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            UserName = "CasualUser69420"
                        },
                        new
                        {
                            Id = new Guid("8c8dd0dd-a6b6-478d-a298-1011cb5bf060"),
                            ChiliUserRoleId = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Email = "catlover@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEL0+HtHZGcctssHegA6T28jtrmIAuHadjb25KJIrrX4ja6AlCXXFTyFRnORVFuKD9A==",
                            RegistrationDate = new DateTime(2022, 1, 6, 8, 20, 36, 707, DateTimeKind.Local).AddTicks(6233),
                            SecretAnswer = "AQAAAAEAACcQAAAAEKVc1vi8MVcN3p3iddVHat8zjXgpYR1Wu7BZzpfcCiKN3QeuuSnHyInNCzwxBivFWw==",
                            SecretQuestionId = new Guid("f3124fb0-79ce-403b-8cd4-eceafaf2a0ff"),
                            UserName = "CatLover123"
                        },
                        new
                        {
                            Id = new Guid("0da09c36-50ac-44fb-a102-8b528bcbad58"),
                            ChiliUserRoleId = new Guid("39bf46f0-cc42-438f-866c-c20c393a307b"),
                            Email = "nis@chiliboard.de",
                            PasswordHash = "AQAAAAEAACcQAAAAEBzA6WvKNoJrYZJr2bNMv9nqVtizfSrZmfRPksxSV+nA6WHGvpMbTd0FYtVvHHQsnQ==",
                            RegistrationDate = new DateTime(2022, 1, 6, 8, 20, 36, 707, DateTimeKind.Local).AddTicks(6179),
                            SecretAnswer = "AQAAAAEAACcQAAAAENSqp3BOlNJvbUKU0+CnTXrooFYBg1GbtHwQuf4ZZgqstLdMSDGCHKb2V7dxW/95ow==",
                            SecretQuestionId = new Guid("f3124fb0-79ce-403b-8cd4-eceafaf2a0ff"),
                            UserName = "nis"
                        });
                });

            modelBuilder.Entity("UserManagementService.Models.ChiliUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Rolename")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39bf46f0-cc42-438f-866c-c20c393a307b"),
                            Rolename = "Admin"
                        },
                        new
                        {
                            Id = new Guid("372a7671-ab69-4450-b77f-306aeb4eb8f1"),
                            Rolename = "DefaultChiliUser"
                        });
                });

            modelBuilder.Entity("UserManagementService.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UserManagementService.Models.SecurityQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SecurityQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3124fb0-79ce-403b-8cd4-eceafaf2a0ff"),
                            Question = "Was ist Ihr Lieblingsessen?"
                        },
                        new
                        {
                            Id = new Guid("5e1e640d-17cc-4d36-8e50-81deaeb6b215"),
                            Question = "Wie lautet der Geburtsname Ihrer Mutter?"
                        },
                        new
                        {
                            Id = new Guid("f7f78ebd-22d5-4861-893e-7dceee4ee4fe"),
                            Question = "Wie lautet Ihre Lieblingsprimzahl?"
                        });
                });

            modelBuilder.Entity("UserManagementService.Models.ChiliUser", b =>
                {
                    b.HasOne("UserManagementService.Models.ChiliUserRole", "Role")
                        .WithMany()
                        .HasForeignKey("ChiliUserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagementService.Models.SecurityQuestion", "SecretQuestion")
                        .WithMany()
                        .HasForeignKey("SecretQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("SecretQuestion");
                });

            modelBuilder.Entity("UserManagementService.Models.RefreshToken", b =>
                {
                    b.HasOne("UserManagementService.Models.ChiliUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
